eu_elections = {
    "CS": {
        "language": "czech",
        "wikicode": "cs.wikipedia",
        2014: {"article_name": "Volby_do_Evropského_parlamentu_2014"},
        2019: {"article_name": "Volby_do_Evropského_parlamentu_2019"},
    },
    "DK": {
        "language": "danish",
        "wikicode": "da.wikipedia",
        2014: {"article_name": "Europa-Parlamentsvalget_2014"},
        2019: {"article_name": "Europa-Parlamentsvalget_2019"},
    },
    "DE": {
        "language": "german",
        "wikicode": "de.wikipedia",
        2014: {"article_name": "Europawahl_2014"},
        2019: {"article_name": "Europawahl_2019"},
    },
    "EL": {
        "language": "greek",
        "wikicode": "el.wikipedia",
        2014: {"article_name": "Ευρωεκλογές_2014"},
        2019: {"article_name": "Ευρωεκλογές_2019"},
    },
    "FI": {
        "language": "finish",
        "wikicode": "fi.wikipedia",
        2014: {"article_name": "Europarlamenttivaalit_2014"},
        2019: {"article_name": "Europarlamenttivaalit_2019"},
    },
    "FR": {
        "language": "french",
        "wikicode": "fr.wikipedia",
        2014: {"article_name": "Élections_européennes_de_2014"},
        2019: {"article_name": "Élections_européennes_de_2019"},
    },
    "HU": {
        "language": "hungarian",
        "wikicode": "hu.wikipedia.",
        2014: {"article_name": "2014-es_magyarországi_országgyűlési_választás"},
        2019: {"article_name": "2019-es_európai_parlamenti_választás"},
    },
    "IT": {
        "language": "italian",
        "wikicode": "it.wikipedia",
        2014: {"article_name": "Elezioni_europee_del_2014"},
        2019: {"article_name": "Elezioni_europee_del_2019"},
    },
    "NL": {
        "language": "dutch",
        "wikicode": "nl.wikipedia",
        2014: {"article_name": "Europese_Parlementsverkiezingen_2014"},
        2019: {"article_name": "Europese_Parlementsverkiezingen_2019"},
    },
    "PL": {
        "language": "polish",
        "wikicode": "pl.wikipedia",
        2014: {"article_name": "Wybory_do_Parlamentu_Europejskiego_w_2014_roku"},
        2019: {"article_name": "Wybory_do_Parlamentu_Europejskiego_w_2019_roku"},
    },
    "GB": {
        "language": "english",
        "wikicode": "en.wikipedia",
        2014: {"article_name": "2014_European_Parliament_election"},
        2019: {"article_name": "2019_European_Parliament_election"},
    },
    "SV": {
        "language": "swedish",
        "wikicode": "sv.wikipedia",
        2014: {"article_name": "Europaparlamentsvalet_2014"},
        2019: {"article_name": "Europaparlamentsvalet_2019"},
    },
    "ES": {
        "language": "spanish",
        "wikicode": "es.wikipedia",
        2014: {"article_name": "Elecciones_al_Parlamento_Europeo_de_2014"},
        2019: {"article_name": "Elecciones_al_Parlamento_Europeo_de_2019"},
    },
    "SL": {
        "language": "spanish",
        "wikicode": "sl.wikipedia",
        2014: {"article_name": "Volitve_v_Evropski_parlament_2014"},
        2019: {"article_name": "Volitve_v_Evropski_parlament_2019"},
    },
}


hour_mapping = {
    "A": 0,
    "B": 1,
    "C": 2,
    "D": 3,
    "E": 4,
    "F": 5,
    "G": 6,
    "H": 7,
    "I": 8,
    "J": 9,
    "K": 10,
    "L": 11,
    "M": 12,
    "N": 13,
    "O": 14,
    "P": 15,
    "Q": 16,
    "R": 17,
    "S": 18,
    "T": 19,
    "U": 20,
    "V": 21,
    "W": 22,
    "X": 23,
}
