eu_elections = {
    "BE": {
        "language": "dutch",
        "wikicode": "nl.wikipedia",
        2014: {"article_name": "Europese_Parlementsverkiezingen_2014"},
        2019: {"article_name": "Europese_Parlementsverkiezingen_2019"},
    },
    "BG": {
        "language": "bulgarian",
        "wikicode": "bg.wikipedia",
        2014: {"article_name": "Избори_за_Европейския_парламент_(2014)"},
        2019: {"article_name": None},
    },
    "DK": {
        "language": "danish",
        "wikicode": "da.wikipedia",
        2014: {"article_name": "Europa-Parlamentsvalget_2014"},
        2019: {"article_name": "Europa-Parlamentsvalget_2019"},
    },
    "DE": {
        "language": "german",
        "wikicode": "de.wikipedia",
        2014: {"article_name": "Europawahl_2014"},
        2019: {"article_name": "Europawahl_2019"},
    },
    "FR": {
        "language": "french",
        "wikicode": "fr.wikipedia",
        2014: {"article_name": "Élections_européennes_de_2014"},
        2019: {"article_name": "Élections_européennes_de_2019"},
    },
}


hour_mapping = {
    "A": 0,
    "B": 1,
    "C": 2,
    "D": 3,
    "E": 4,
    "F": 5,
    "G": 6,
    "H": 7,
    "I": 8,
    "J": 9,
    "K": 10,
    "L": 11,
    "M": 12,
    "N": 13,
    "O": 14,
    "P": 15,
    "Q": 16,
    "R": 17,
    "S": 18,
    "T": 19,
    "U": 20,
    "V": 21,
    "W": 22,
    "X": 23,
}
